connections/github.py

Code was prepared to renew the token which expires normally after an hour. There was a slight mismatch in naming the variable holding the token: `token` vs `_token`.
This PR address one scenario of #20 (the issue should be kept open because there may be other scenarios in which the bot should tolerate communication failures).

Fixing renewal of expired access token

---

.gitignore
README.md
app.cfg.example
connections/github.py
eessi_bot_job_manager.py
eessi_bot_job_monitor.py
eessi_bot_software_layer.py
job_manager.sh
requirements.txt
run.sh
scripts/eessi-bot-build.slurm
tasks/build.py
tools/args.py

This is a larger pull request. Among a few smaller changes (e.g., adding ability to specify port on which the bot listens, makes PR #22 obsolete, sorry) it adds functionality to monitor the status of jobs, then checks the result of finished jobs and updates the PR accordingly.
The monitoring implements option 1 in #12. This is a bit inelegant -- it only uses `squeue` because `sacct` wasn't available on the CitC cluster on AWS and uses `pandas` to read in the output from `squeue` which might be overkill. An improvement would be to enable the bot monitoring jobs even after it has crashed (see #23). A future version of the bot could have different implementations for monitoring the jobs and then select the best one based on what is available on a cluster (`sacct` or `squeue`). Also, one …

Check build job status and comment on PR

---

README.md
app.cfg.example
eessi_bot_event_handler.py
eessi_bot_job_manager.py
scripts/eessi-upload-to-staging
tasks/build.py
tasks/deploy.py

This is based on recent updates/improvements/refactoring of the EESSI bot. It includes the implementation of the deploy step, new configuration settings and their documentation in the README.md.
It is ~still work-in-progress for two reasons~ ready for getting reviewed:
- The documentation ~lacks~ includes information on setting up some tools needed by the upload script.
- It has ~not~ been tested ~yet~.
Nice addition compared to #49 is that the bot can be configured to restrict who can set the `bot:deploy` label.

working implementation of 'deploy' step

---

eessi_bot_job_manager.py

Tested on AWS cluster (see https://github.com/trz42/software-layer/pull/46#issuecomment-1319511323). Will run a final test using this PR as it includes recently merged PRs (no conflicts) and minor tweaks to the logging from the job manager.
Follow-up to #63 
Closes #33

Fix non-bot jobs leaking into `known_jobs` + make sure that job manager logs to correct file

---

connections/github.py
eessi_bot_job_manager.py
tasks/build.py
test.sh
tests/test_task_build.py
tools/__init__.py
tools/config.py

The following changes have been made:
- On error, run_cmd raises a RuntimeError in addition to logging the error message.
- Slurm errors are logged in the case of states "Failure", "Out of Memory" or "Time Out". I opted not to log issues due to "Pending: ReqNodeNotAvail", because this can either mean that the node is fully in use and is unable to run any more jobs, which isn't an error, or it can mean that there is a problem with the node and it is offline. I did not see a way to differentiate between these two cases. A "warning" could be appropriate here, but I thought that may be annoying if it happens too often.
- Errors are logged when token creation fails, due to missing configuration parameters.
- From what I could tell, /tools/config.py was using the wrong method to read the config …

Error handling

---

connections/github.py

retry after exception

---

tasks/build.py

The `.patch` patch file contains individual commits, rather than just a `diff` against current target branch, see https://github.com/EESSI/software-layer/pull/210.patch vs https://github.com/EESSI/software-layer/pull/210.diff
By using `.patch`, problems pop up when trying to apply the patch if merge conflicts were involved in the PR.
That shouldn't be a problem when using the `.diff` patch file instead to set up the build job directory...

use .diff patch file to set up build job working directory

---

tasks/build.py

Added 24h default time limit

---

README.md
app.cfg.example
eessi_bot_event_handler.py
tasks/build.py
tasks/deploy.py
tests/test_app.cfg
tests/test_task_build.py
tests/test_tools_filter.py
tests/test_tools_pr_comments.py
tools/commands.py
tools/filter.py
tools/permissions.py
tools/pr_comments.py

This PR probably needs some updates/polishing but it has been tested already with a few PRs to the software-layer repository. It includes the following additions:
- class to model action filters where an action is something like submitting a build job
- compared to setting a label `bot:build` an action can be filtered wrt a repository, an architecture and a bot instance name
- idea is that an action is only performed if its context (repository, architecture and bot instance) matches the filter
- class to model bot commands which are composed of a command such as `help` and `build` and an action filter
- adds code to parse *NEW* comments for bot commands (beginning at the start of a line with `bot: `), displays if a command has been received, processes the command(s) and adds some …

support for sending commands to bot instances via PR comments

---

eessi_bot_job_manager.py
scripts/bot-build.slurm

While writing the [documentation for the bot](https://www.eessi.io/docs/bot/), I realized that `check-result.sh` is a bit of a misnomer, since eventually we may also want a `check-test.sh` and `check-deploy.sh` script.
By still considering `check-result.sh` as a fallback when `check-build.sh` is not there, we can transition easily to `check-build.sh` without causing trouble...

prefer bot/check-build.sh script over bot/check-result.sh in build job script

---

app.cfg.example
tasks/build.py

Add support for specifying path to build logs directory, to which `bot/build.sh` script should copy build log for failing builds.
This way, contributors can access the build log of failing builds, if they have an account on the Slurm cluster where the bot is running and is configured with `build_logs_dir` set to a readable directory on a shared filesystem.

add support for specifying path to build logs directory

---

RELEASE_NOTES

add RELEASE_NOTES for v0.1.0

---

eessi_bot_job_manager.py

Adds `--noheader` argument to `squeue` command and then parses all output lines to determine current jobs.
Fixes #219

omit header in squeue output

---

connections/github.py
requirements.txt

I tested the changes with python 3.8
resolves the following issue: https://github.com/EESSI/eessi-bot-software-layer/issues/223

Upgrade bot to be compatible with PyGithub v2.1.1

---

README.md
app.cfg.example
tasks/build.py
tasks/deploy.py

With this in place, we should be able to specify the bucket in the bot configuration as follows:
```ini
bucket_name = {
"eessi-hpc.org-2023.06-compat": "eessi-staging-2023.06",
"eessi-hpc.org-2023.06-software": "eessi-staging-2023.06",
"eessi.io-2023.06-compat": "software.eessi.io-2023.06",
"eessi.io-2023.06-software": "software.eessi.io-2023.06",
}
```
which effectively allows us to let the bot use different buckets for different target repos (and even different buckets for different repo versions, or different buckets for compat vs software layer, etc.)
By checking the value type of `bucket_name`, we can ensure that current bot instances that use a hardcoded bucket name as string value will not be affected, so this change is backwards-compatible.

add support for specifying bucket name as mapping with repo id as key

---

README.md
app.cfg.example
tasks/build.py
tests/test_task_build.py
tests/test_tools_filter.py

Mostly changes in examples, README.md and tests. Only a single code file (`tasks/build.py`) had to be changed.
Implementation (use with bot instances) should be coordinated with software-layer PR https://github.com/EESSI/software-layer/pull/383

remove references to 'pilot', switch to software.eessi.io

---

README.md
app.cfg.example
eessi_bot_job_manager.py
scripts/bot-build.slurm

- Adds the necessary steps to the Slurm job script.
- Adds handling of the result of the test suite run (i.e., updating the PR comment).
- Adds one config setting `job_test_unknown_fmt` and corresponding description.
Also see accompanying PR for software-layer https://github.com/EESSI/software-layer/pull/366
edit (by @boegel): it's worth noting that these changes will require adding `job_test_unknown_fmt` to  the bot configuration file, or the job manager will crash with:
```
...
File "/home/boegel/eessi-bot-software-layer/eessi_bot_job_manager.py", line 572, in process_finished_job
job_test_unknown_fmt = finished_job_comments_cfg[JOB_TEST_UNKNOWN_FMT]
File "/usr/lib64/python3.6/configparser.py", line 1233, in __getitem__
raise KeyError(key)
KeyError: 'job_test_unknown_fmt'
```
when …

add support to run test suite at the end of a build job

---

eessi_bot_event_handler.py
tasks/build.py

The command creates a comment that contains a table with all the builds done in the pr where the command is called. 
example: 
- https://github.com/laraPPr/software-layer/pull/4#issuecomment-1910007732

New bot command `bot: status`

---

connections/github.py

The job manager crashes too often. An expired GH access token could be the reason for a crash with the error
```
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```
Such messages were reported in issue #142 
This PR attempts to prevent such crashes by renewing the GH access token before it has actually expired. Normally, it's valid for an hour. With this PR it will be renewed if it is valid for less than 30 minutes. Hence, there should be more time from actually checking the validity of the token and using it.

renew GitHub access token ahead of time to prevent "`Bad credentials`" crashes

---

eessi_bot_job_manager.py
tests/test_eessi_bot_job_manager.py
tests/test_tools_job_metadata.py
tools/job_metadata.py

This is a small change moving code that is used in `eessi_bot_job_manager.py` into a function defined in `tools/job_metadata.py` and then use that function in `eessi_bot_job_manager.py`.
It's a step towards syncing the codes of the NESSI and EESSI bots.

add function that reads PR section from job metadata and use it in job manager

---

tasks/deploy.py

This is a follow up PR to sync bot codes used for EESSI and NESSI. It includes the following changes
- adds function `determine_pr_comment_id` which reads the attribute `pr_comment_id` from the job's metadata file (all current bot instances already provide that attribute when creating the job's metadata file)
- the function is then used when successful jobs are determined (in function `determine_successful_jobs`) and the comment id is added to a dictionary that contains information for each job
- another function (`determine_tarballs_to_deploy`) adds the comment id to a dictionary storing information about jobs/tarballs to deploy
- also includes slight code readability improvement by replacing a one letter variable name (`s`) with a more descriptive name (`job`)

add function to determine comment id for a job and use it

---

README.md
app.cfg.example
scripts/eessi-upload-to-staging
tasks/build.py
tasks/deploy.py

This is the final PR to sync bot codes used by NESSI and EESSI. Essentially it provides two parts:
- changes to upload location of the tarball and the corresponding metadata file
- any fixes to bugs that were potentially introduced by recent PRs:
- #247,
- #249,
- #250, _and_
- #253
- includes two small changes/additions 
- https://github.com/EESSI/eessi-bot-software-layer/pull/254/commits/3a2df5af805025785131df9fc76967bf3f6b6e2f (report download status also in case of success)
- https://github.com/EESSI/eessi-bot-software-layer/pull/254/commits/bbfb21bec6109f4c7b8b65443f33284bc7c5c6dc (obtain target architecture from comment when processing the `bot: status` command)
- updates `README.md` to include new and missing settings 
The PR has been extensively tested through multiple PRs with …

make upload directory in S3 bucket configurable

---

eessi_bot_event_handler.py
tools/commands.py

This let the bot only respond to comments which contain a bot command. If so it will either process the command if the sender is authorised to send commands to the bot or it will just respond with a note that the sender is not authorised.
The PR has been tested by letting two different accounts (one authorised, one not authorised) send comments with and without bot commands. See comment https://github.com/trz42/software-layer/pull/72#issuecomment-1965222781 and below.
The PR essentially adds a new function `contains_any_bot_command` and rearranges the processing in `handle_issue_comment_event` by first checking if the comment was newly created (only newly created comments are considered for processing bot commands), then checking if it contains any bot command, then proceeding with the …

only respond to bot commands

---

RELEASE_NOTES

Bug fixes:
* fixes issue using wrong values when using the `bot: status` command (#251)
Improvements:
* the bot report when downloading the pull request's contents failed (#248)
* adding the pull request comment id to the metadata file that is uploded to the
the S3 bucket (#247, #249, #250, #253)
* enabling configurable upload directories for tarball and metadata file (#254)
* the bot only responds to pull request comments that contain a bot command (#257)

release notes for v0.4.0

---

eessi_bot_event_handler.py

Shortens the list of "build targets" (architectures and repository ids). This is shown when a PR is opened or for the command `bot: show_config`. Tested in https://github.com/trz42/software-layer/pull/72
Example:
Instance `dev-PR254` is configured to build:
- arch `x86_64/amd/zen2` for repo `nessi-2022.11-swl-deb10`
- arch `x86_64/amd/zen2` for repo `nessi-2023.06-cl`
- arch `x86_64/amd/zen2` for repo `nessi-2023.06-swl-deb10`
- arch `x86_64/amd/zen2` for repo `nessi-2023.06-swl-deb11`
- arch `aarch64/generic` for repo `nessi-2022.11-swl-deb10`
- arch `aarch64/generic` for repo `nessi-2023.06-cl`
- arch `aarch64/generic` for repo `nessi-2023.06-swl-deb10`
- arch `aarch64/generic` for repo `nessi-2023.06-swl-deb11`
- arch `aarch64/thunderx2` for repo `nessi-2022.11-swl-deb10`
- arch …

Improve display of build targets

---

README.md
app.cfg.example
eessi_bot_job_manager.py
scripts/eessi-upload-to-staging
tasks/deploy.py
tests/test_app.cfg
tests/test_tools_job_metadata.py
tools/job_metadata.py

This is a long awaited PR for making the bot more agnostic to what it builds for. Specifically this removes code in the deployment procedure that was only correct for deploying tarballs created by build jobs for the (EESSI) software-layer.
It contains necessary changes in the logic but also some improvements to reduce boiler-plate code (handling/reading of information from `ini`/`cfg`-type files) and some renaming of variables, functions and log messages.
Below is a breakdown of the major changes
- file `tasks/deploy.py`
- uses `get_section_from_file` (`tools/job_metadata.py`) to read job metadata and return `PR`
section
- renames function `determine_eessi_tarballs` to `determine_artefacts`
- uses `_bot_jobSLURM_JOBID.result` file to obtain list of artefacts (previously named tarballs)
- …

use result files for deployment

---

connections/github.py
eessi_bot_event_handler.py
eessi_bot_job_manager.py
tasks/build.py
tasks/deploy.py
tools/config.py
tools/cvmfs_repository.py
tools/job_metadata.py
tools/permissions.py

This PR turned out to be larger than originally intended (just validating that required config settings are defined when bot components start). However, it reorganises / brings consistent structure to how and where string constants are defined. Hopefully, this makes the code easier to read.
- string constants being used have been defined in the correct modules
- when they are used they have to be prefixed with the module, hence it becomes more clear to which module they belong
- a new file tools/cvmfs_repository.py for constants used for the settings of a CernVM-FS repository is added
- both the event handler and job manager verify at the start that required/recommended settings are defined in 'app.cfg'
TODO
- various tests ran in https://github.com/trz42/software-layer/pull/74 
- added …

reorganisation of constants and validation of config settings

---

eessi_bot_event_handler.py

This PR modifies the clean up code such that data of PRs is moved to a trash bin directory also in case the PR was closed.
~WIP because it's not been tested yet.~ Has been tested by @Neves-P. Thanks!

handle closed PRs too

---

tests/test_tools_filter.py
tools/filter.py

This is a first PR towards better support for building for GPUs. It includes the following changes/additions:
- a new filter component `accelerator` (that can be added to to `bot: build ...` commands)
- adjusted processing of filter component names so that components must be given with at least three characters
- improved definition and use of strings for raising exceptions if anything went wrong with providing filters
- fixed code for removal of filters (the code was neither used nor tested, thus we were not aware that it would not always work)
- added tests for the removal of filters and for the new filter component (`accelerators`)
- updated tests that were broken by code changes

add filter for accelerators and pytests

---

tasks/build.py

required for downloading from a private repo using a github token.

use github API for downloading the diff

---

README.md

Note that we can discuss if this is the right place for this documentation, since the bot is (in principle) generic. However, if we put this in `software-layer` itself, I'm afraid people deploying bot instances to build for the EESSI software layer will not find it. For now, I think this is the best place.
Imho, I'd think that _all_ documentation currently in the `README.md` should eventually move to the https://eessi.io/docs pages anyway for better visibility, but that's not urgent. In any case, that'll resolve the question of where to put this part that is slightly software-layer specific, as it _definitely_ is appropriate on https://eessi.io/docs.

Added information in README.md on how to create a ReFrame configuration file for the `software-layer` test step

---

scripts/bot-build.slurm

This is what I'm using for [this build](https://github.com/EESSI/software-layer/pull/903#issuecomment-2638547844), which was succesful.
It resolves the issue I had that a having a `TMPDIR` set on a system would cause `mktemp` in the `create_tarball.sh` to error out, because the `TMPDIR` wasn't available in the container. The fundamental issue is that `local_tmp` is not unique, so we don't want to bind-mount that directly into the container, as it might be shared between jobs. 
In this PR, we use the `local_tmp` that is configured and use `mktemp` to create a new directory within. That's what we will then use as the `TMPDIR`. This ensures that the `app.cfg` fully controls the `TMPDIR` used. Note that one can _still_ define `local_tmp = \$TMPDIR` if one wants to use the `TMPDIR` that would …

Set the local_tmp that is configured for a site as tmpdir

---

tasks/deploy.py

Apparently launching a container may run some initialisation scripts from the host inside the container. This is likely not needed nor desired. This small PR adds the option `--contain` to when we launch a container to run the script that uploads files to an S3 bucket.

avoid that host initialisation scripts are run when launching container

---

.github/workflows/tests_scripts.yml
scripts/eessi-upload-to-staging
scripts/sign_verify_file_ssh.sh
tasks/deploy.py

Use the bot instance's name as the namespace when signing files. Both sign and verify steps are updated. The verification is also prepared to support additional options such as `valid-before`.
CI tests are adjusted and extended to cover new functionality.
Part of CI output (added tests):
```
Verifying the signature against allowed signers...
Checking principal: wrong_namespace_identity and namespace: CI
Couldn't verify signature: namespace does not match
Could not verify signature.
Error: No valid signature found.
Expected failure for wrong namespace
Verifying the signature against allowed signers...
Checking principal: expired_key_identity and namespace: ci
allowed_signers:1: key has expired: verify time 2025-03-14T21:23:43 > valid-before 2025-03-11T00:00:00
Could not verify signature. …
```

use bot name as namespace

---

eessi_bot_event_handler.py
tools/commands.py

Set a default `self.build_params = None` on constructiong the `EESSIBotCommand`. Then, in handling the bot build command, don't submit a job if `self.build_params` wasn't defined
fixes #330

Make sure to print an informative message to the log when a `for:` argument is missing

---

eessi_bot_job_manager.py

required bug fix for enhancement implemented in #327, to keep placeholder and allow processing jobs that require different placeholder values
Without this, the first job that's processed determines the value for a placeholder like `%(cluster)s`, but multiple jobs being processed/released in sequence may belong to different clusters

don't replace self.scontrol_command in process_new_job

---

eessi_bot_event_handler.py
tools/commands.py

This PR implements functionality so that one can do:
```
bot:status last_build
```
Which will create a status table only contain the last build for each `for` architecture. This makes it _much_ easier to check if all architectures have been (successfully) build for in a given PR. That's almost essential for GPU builds, where the number of target architectures is currently 13 (CPU) * 3 (GPU) = 39 architectures.
[This example](https://github.com/casparvl/software-layer-scripts/pull/2#issuecomment-3201357360) was created with a bot running from [this commit](https://github.com/EESSI/eessi-bot-software-layer/pull/334/commits/7b284ba8d83688d4104b880f5c3484d0bb87c0b0)
Fixes https://github.com/EESSI/eessi-bot-software-layer/issues/332

Add option to bot:status to print the status only for the last build

---

RELEASE_NOTES

release notes for v0.9.0
