- tasks/build.py
> added methods for refactoring

- tasks/build.py
Mainly making this PR to test Hound CI configuration that was added in [021a9ff](https://github.com/EESSI/eessi-bot-software-layer/commit/021a9ffc4d8cb68f226de11c7569f11c075c1944)...
> fix trivial code style issues in tasks/build.py

- .github/workflows/tests.yaml
- test.sh
- tests/test_task_build.py
First step towards proper test suite for bot (see #38)
> add test for mkdir function + CI workflow to run tests with Python 3.6 - 3.11

- eessi_bot_event_handler.py
- tasks/build.py
> Additional refactoring in build.py

- connections/github.py
- eessi_bot_event_handler.py
- eessi_bot_job_manager.py
- event_handler.sh
- job_manager.sh
- scripts/eessi-bot-build.slurm
- tasks/build.py
- tests/test_task_build.py
- tools/args.py
- tools/config.py
- tools/logging.py
Added missing info about the purpose of a file. Added missing authors. Added missing license info.
> Update file headers

- tests/test_task_build.py
See https://github.com/EESSI/eessi-bot-software-layer/issues/64.
> Pass flake8 tests for tests/test_task_build.py

- tools/args.py
See https://github.com/EESSI/eessi-bot-software-layer/issues/64.
> Pass flake8 tests for tools/args.py

- tools/config.py
See https://github.com/EESSI/eessi-bot-software-layer/issues/64.
> Pass flake8 tests for tools/config.py

- tools/logging.py
See https://github.com/EESSI/eessi-bot-software-layer/issues/64.
> Pass flake8 tests for tools/logging.py

- .github/workflows/tests.yaml
> Add flake8 checks

- scripts/eessi-upload-to-staging
This script is moved from EESSI/infrastructure to EESSI/eessi-bot-software-layer. See https://github.com/EESSI/eessi-bot-software-layer/pull/62#discussion_r1023986542 for background information. The exact same version of the script should be removed from the infrastructure repository with PR https://github.com/EESSI/infrastructure/pull/74.
> add script to upload tarball to S3 bucket

- eessi_bot_job_manager.py
- tests/test_task_build.py
- tools/__init__.py
> implemented the run_cmd everywhere

- eessi_bot_event_handler.py
- eessi_bot_job_manager.py
- tools/args.py
> split up option parsers for event handler and job manager

- eessi_bot_job_manager.py
> determine_username

- eessi_bot_job_manager.py
- tools/pr_comments.py
> identify pr comment to be updated

- LICENSE
> Add LICENSE (GPLv2)

- eessi_bot_event_handler.py
> improve start of the app

- app.cfg.example
- eessi_bot_event_handler.py
- tasks/build.py
> check build permission

- eessi_bot_job_manager.py
> added comment in pr for showing running state of the jobs

- .flake8
- .hound.yml
- eessi_bot_job_manager.py
- tasks/deploy.py
- tests/test_task_build.py
- tools/__init__.py
This wraps PR #77 in an attempt to fix its merge conflicts.
> improve error handling

- connections/github.py
- eessi_bot_event_handler.py
- eessi_bot_job_manager.py
- tasks/build.py
- tasks/deploy.py
- tools/config.py
> generic read_config method in tools/config.py

- scripts/eessi-bot-build.slurm
- tasks/build.py
> let bot pass CPU target to build for to build job script, and use it to set $EESSI_SOFTWARE_SUBDIR_OVERRIDE

- scripts/eessi-bot-build.slurm
No changes to the code in the `else` part, keeping that as fallback now so we can keep building PRs even if no `bot/build.sh` script exists yet...
> run bot/build.sh script in build job script, if it exists

- requirements.txt
- tests/test_tools_pr_comments.py
- tools/pr_comments.py
> try and except in pr_comments.py

- eessi_bot_job_manager.py
- tests/test_eessi_bot_job_manager.py
Fix for issue #133 and related tests as described in #150
> Fix for bug in determine_running_jobs in job_manager

- README.md
- app.cfg.example
- tasks/deploy.py
> Renamed upload_to_s3_script to tarball_upload_script

- eessi_bot_job_manager.py
modifying code to consider all jobs by job manager
fixes #165
> modifying code to consider all jobs by job manager

- app.cfg.example
- eessi_bot_job_manager.py
Fix for #173 , which is issues from #170
> Fixed typos from PR170

- eessi_bot_event_handler.py
Small PR to make sure no one is launching dozens of build jobs by setting the bot:build label.
> disable bot:build label + log and create PR comment

- connections/github.py
Code polishing pass on `connections/github.py` for release v0.1:
- imports: same structure, alphabetical order
- docstrings: added using same structure
- comments: added some, moved some to docstrings
> [v0.1] code polishing: connections/github.py

- tools/permissions.py
Code polishing pass on `tools/permissions.py` for release v0.1:
- imports: same structure
- docstrings: added some missing information
- comments: clarified
> [v0.1] code polishing: tools/permissions.py

- tools/commands.py
Code polishing pass on `tools/commands.py` for release v0.1:
- imports: same categorisation of imports
- docstrings: slightly rephrased some + added a missing information
- comments: added a TODOs for future improvements
> [v0.1] code polishing: tools/commands.py

- tools/logging.py
Code polishing pass on `tools/logging.py` for release v0.1:
- imports: same structure (some sections/categories are empty), removed one unused import (`json` was needed for a removed function)
- docstrings: added args and returns
- comments: added a comment regarding fixed location+name of log file
- functions: removed unused function `log_event`
> [v0.1] code polishing: tools/logging.py

- tools/job_metadata.py
Code polishing pass on `tools/job_metadata.py` for release v0.1:
- imports: same categorisation of imports, removing commented imports
- docstrings: slightly rephrased some + added a missing information
- comments: improved some comments + added a TODO for future improvements
> [v0.1] code polishing: tools/job_metadata.py

- tools/args.py
Code polishing pass on `tools/args.py` for release v0.1:
- imports: added comments for categories of imports
- docstrings: added missing information
> [v0.1] code polishing: tools/args.py

- tools/__init__.py
Code polishing pass on `tools/__init__.py` for release v0.1:
- imports: add comments for categorising imports
- docstrings: slightly rephrased some docstrings + added a bit more information on exceptions raised
- comments: added TODOs for future improvements
> [v0.1] code polishing: tools/__init__.py

- tools/filter.py
Code polishing pass on `tools/filter.py` for release v0.1:
- imports: same categorisation of imports
- docstrings: slightly rephrased some + added a missing information
- comments: improved some comments
> [v0.1] code polishing: tools/filter.py

- tasks/deploy.py
Code polishing pass on `tasks/deploy.py` for release v0.1:
- imports: same categorisation of imports
- ordered constant definitions alphabetically
- docstrings: slightly rephrased some + fixed some wrong data types + added a missing information
- comments: improved some comments
> [v0.1] code polishing: tasks/deploy.py

- eessi_bot_event_handler.py
Code polishing pass on `eessi_bot_event_handler.py ` for release v0.1:
- imports: same categorisation of imports + ordered imports alphabetically
- docstrings: improved and completed docstrings
- comments: improved and removed some comments
> [v0.1] code polishing: eessi_bot_event_handler.py

- eessi_bot_job_manager.py
Code polishing pass on `eessi_bot_job_manager.py` for release v0.1:
- imports: same categorisation of imports + ordered imports alphabetically
- ordered constant definitions alphabetically
- docstrings: improved and completed docstrings
- comments: improved and cleaned up comments
> [v0.1] code polishing: eessi_bot_job_manager.py

- README.md
- app.cfg.example
- tasks/build.py
~WIP because I'm still testing whether this works as expected, see also companion PR https://github.com/EESSI/software-layer/pull/337~
Works as expected, testing along with https://github.com/EESSI/software-layer/pull/337 via https://github.com/boegel/software-layer/pull/27
> add `shared_fs_path` configuration setting

- RELEASE_NOTES
adding release notes for v0.1.1 and updating `main` branch
> release v0.1.1

- README.md
- RELEASE_NOTES
- connections/github.py
- eessi_bot_job_manager.py
- scripts/cleanup_pr.sh
Update main, then tag release v0.1.1.
> merge v0.1.1 into main

- RELEASE_NOTES
Includes
- new bot command `bot: status` #237
- fix for preventing some crashes of the job manager #238
> release notes for v0.3.0

- scripts/eessi-upload-to-staging
- tasks/deploy.py
Another PR for syncing bot source codes used by EESSI and NESSI.
- passes PR comment id to script used for uploading tarball and metadata file to S3 bucket
- script extended to use additional argument and to add the PR comment id to the uploaded metadata file
> add PR comment id to uploaded metadata

- RELEASE_NOTES
Small update to release notes to take @boegel's comments into account.
> improve release notes for v0.4.0

- RELEASE_NOTES
Includes a short update about the changes included in release v0.5.0
> release notes for v0.5.0

- RELEASE_NOTES
> release notes for v0.6.0

- eessi_bot_event_handler.py
In this PR, the bot will only write a comment when a PR is closed if any directories were actually moved to the `trash_bin`. Without this, bots that didn't build anything but are listening on PRs will still comment that an empty list was moved to the trash bin directory.
I have not yet tested this live on a bot build, but can do so on the dev.eessi.io bot
This PR is related to #290 but does fix it.
> Bot only reports moving to trash_bin when relevant

- RELEASE_NOTES
Tentative notes for the next release.
> release notes for v0.7.0

- .github/workflows/tests.yaml
- connections/github.py
- test.sh
Runs `pytest` twice once without and once with `--cov` to determine coverage of tests.
> determine test coverage

- RELEASE_NOTES
Tentative notes for the next release.
> release notes for v0.8.0
